version: "3.8"
services:
  frontend:
    build: ./frontend
    volumes:
      - ".:/application"
    ports:
      - 3000:3000
  server:
    build: ./server
    volumes:
      - ".:/application"
    environment:
      MY_SECRET: "this is the secret"
    ports:
      - 4000:4000
